### ISSUE TITLE
[IMPROVE] Custom 'Guest' Avatar setting

### ISSUE THREAD

**Issue by dlassalle** [WideChat/Rocket.Chat.Livechat#14]
This is likely a change that needs to happen in the RC core, in which case please use the develop_livechat branch for widechat

Currently when unregistered guests start to chat, they are assigned a name 'guest-1234' and their icon shows up as 'G'.

Add a setting to livechat where we can set a guest's default icon

**Comment by shubhsherl** [comment]
@dlassalle Currently the guest avatar are not in sync, the avatar on RC is based on username, while the avatar on livechat is based on name(if name is null then username), how should be the behaviour of custom guest avatar be like, in that case.
![livea_agent_003](https://user-images.githubusercontent.com/34231951/89252547-ae0f3900-d637-11ea-9108-85624cf51fb0.png)
