### ISSUE TITLE
[IMPROVE] visibility of 'End Chat' button

### ISSUE THREAD

**Issue by dlassalle** [WideChat/Rocket.Chat.Livechat#6]
- Button to end the chat should always be visible
- User should be able to re-open the widget to start a new session without refreshing the page
- Button should act the same as the finish chat one, where it asks the user to confirm they want to end the session, and offers them a transcript (if enabled)

**Comment by Shailesh351** [comment]
@KashishJagyasi Can you help with the UI for this one? Thanks in advance 😊

**Comment by Shailesh351** [comment]
@dlassalle How it looks? And also if we add this, do we need to remove the Finish Chat from the options menu? Because it's same functionality 
![localhost_8080_](https://user-images.githubusercontent.com/18264684/91310153-21d3da00-e7cf-11ea-9de6-be9825f0ed49.png)

**Comment by dlassalle** [comment]
( another ping @KashishJagyasi in case she has opinions)
Hmm, maybe it would make more sense to have the changes i've circled in blue here, since the 'X' doesnt actually kill the chat, it just minimizes it? 

In the mock-up below, the 'X' at the top right would have the 'end chat' functionality

And no, we dont need to remove the finish chat option in the menu

![91310153-21d3da00-e7cf-11ea-9de6-be9825f0ed49](https://user-images.githubusercontent.com/15149385/91333051-0c44bd00-e79b-11ea-8e86-f79a3f93cbc4.png)
