### ISSUE TITLE
[FEATURE REQUEST] Allow for disabling of user input if message attachment payload exists

### ISSUE THREAD

**Issue by dlassalle** [WideChat/Rocket.Chat.Livechat#9]
- When a bot service sends a payload for disabling input, the user't text-entry box should be greyed out and display the `disabpleInputMessage` string
- The input should be disabled as long as the most recent message from the agent/bot contains the disable payload, any message that does not have the disable payload should remove the input block

Example payload
```
{
  "disableInputMessage": "Please wait",
  "disableInput": true
}
```

- This payload would be added as a message attachment  of type 'action' in client

Screenshots of another client's performance:

![Screen Shot 2020-07-01 at 8 16 12 AM](https://user-images.githubusercontent.com/15149385/86242780-3a2ecc00-bb73-11ea-8926-e0cf50010ca1.png)
![Screen Shot 2020-07-01 at 8 16 31 AM](https://user-images.githubusercontent.com/15149385/86242782-3a2ecc00-bb73-11ea-9223-8eff792a0191.png)

These payloads will be added as part of https://github.com/RocketChat/Apps.Dialogflow/issues/29, so it may be the coming from custom-field rather than attachments..

**Comment by shubhsherl** [comment]
@dlassalle How will we show the `disableInputMessage`. Also, right now, we are not handling any custom fields in the message, right?
![rc_live](https://user-images.githubusercontent.com/34231951/88626920-148cd800-d0c9-11ea-8661-2b30be7ec3d8.png)

This one I found in https://github.com/WideChat/Rocket.Chat/wiki/UX-Improvements-Milestone-%232  but it does not have any `disableInputMessage`.
![](https://user-images.githubusercontent.com/47213420/88195602-d8d3b780-cc5d-11ea-8ff1-e2e5fb3c69a3.png)

**Comment by ear-dev** [comment]
@ear-dev ask Kashish about design for when input box is disabled.

**Comment by dlassalle** [comment]
Disable input is going to be a feature of UIKit that is in the works with app-engine, which would allow the disable to happen dynamically.
I'd opt for leaving this for now and waiting for that feature to roll-out

**Comment by shubhsherl** [comment]
![2020-09-14-162236_1135x823_scrot](https://user-images.githubusercontent.com/34231951/93079053-217d7f00-f6a9-11ea-8b51-0deab1da2380.png)
